import { useState } from 'react';
import type { Message } from '@decodr/types';
import { MessageRole } from '@decodr/types';
import { Badge, Card } from '@/components/ui';
import { Markdown } from './Markdown';

const CONTEXT_PREVIEW = 5;

export function ChatMessages({ messages }: { messages: Message[] }) {
  return (
    <div className="space-y-4">
      {messages.map((message) =>
        message.role === MessageRole.User ? (
          <UserBubble key={message.id} content={message.content} />
        ) : (
          <AssistantCard key={message.id} message={message} />
        ),
      )}
    </div>
  );
}

function UserBubble({ content }: { content: string }) {
  return (
    <div className="flex justify-end">
      <div className="max-w-[85%] rounded-2xl rounded-br-md border border-primary/30 bg-primary/10 px-4 py-2.5 text-sm text-foreground">
        {content}
      </div>
    </div>
  );
}

function AssistantCard({ message }: { message: Message }) {
  const [expanded, setExpanded] = useState(false);
  const total = message.contextPaths.length;
  const shown = expanded ? message.contextPaths : message.contextPaths.slice(0, CONTEXT_PREVIEW);
  const hidden = total - shown.length;

  return (
    <Card className="p-5">
      <Markdown content={message.content} />
      {total > 0 && (
        <div className="mt-4 border-t border-border pt-3">
          <p className="mb-2 text-[11px] uppercase tracking-wide text-subtle">
            Context · {total} file{total === 1 ? '' : 's'}
          </p>
          <div className="flex flex-wrap items-center gap-1.5">
            {shown.map((path) => (
              <Badge key={path} className="font-mono">
                {path}
              </Badge>
            ))}
            {total > CONTEXT_PREVIEW && (
              <button
                type="button"
                onClick={() => setExpanded((v) => !v)}
                className="rounded-full border border-border px-2.5 py-0.5 text-[11px] font-medium text-muted transition-colors hover:border-border-strong hover:text-foreground"
              >
                {expanded ? 'Show less' : `+${hidden} more`}
              </button>
            )}
          </div>
          {message.model && (
            <p className="mt-3 text-[11px] text-subtle">Generated by {message.model}</p>
          )}
        </div>
      )}
    </Card>
  );
}
