import type { Message } from '@arcloom/types';
import { MessageRole } from '@arcloom/types';
import { Badge, Card } from '@/components/ui';
import { Markdown } from './Markdown';

export function ChatMessages({ messages }: { messages: Message[] }) {
  return (
    <div className="space-y-4">
      {messages.map((message) =>
        message.role === MessageRole.User ? (
          <UserBubble key={message.id} content={message.content} />
        ) : (
          <AssistantCard key={message.id} message={message} />
        ),
      )}
    </div>
  );
}

function UserBubble({ content }: { content: string }) {
  return (
    <div className="flex justify-end">
      <div className="max-w-[85%] rounded-2xl rounded-br-md border border-primary/30 bg-primary/10 px-4 py-2.5 text-sm text-foreground">
        {content}
      </div>
    </div>
  );
}

function AssistantCard({ message }: { message: Message }) {
  return (
    <Card className="p-5">
      <Markdown content={message.content} />
      {message.contextPaths.length > 0 && (
        <div className="mt-4 border-t border-border pt-3">
          <p className="mb-2 text-[11px] uppercase tracking-wide text-subtle">
            Context · {message.contextPaths.length} file
            {message.contextPaths.length === 1 ? '' : 's'}
          </p>
          <div className="flex flex-wrap gap-1.5">
            {message.contextPaths.map((path) => (
              <Badge key={path} className="font-mono">
                {path}
              </Badge>
            ))}
          </div>
          {message.model && (
            <p className="mt-3 text-[11px] text-subtle">Generated by {message.model}</p>
          )}
        </div>
      )}
    </Card>
  );
}
